version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DATABASE_URL=mariadb://gnj@platform-gnj-mariadb-dev:English@12345@platform-gnj-mariadb-dev.mariadb.database.azure.com:3306/mydb?sslmode=require
